spring:
  application:
    name: spring-ai-rag
  #Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: mistral
      embedding:
        model: nomic-embed-text  # Вместо стандартной модели
#    chat:
#      model: gpt-oss
#    openai:
#      api-key: ${OPENAI_API_KEY}
sfg:
  aiapp:
    vectorStorePath: src/main/resources/vectorstore.json
    documentsToLoad:
      - classpath:/movies500Trimmed.csv